### ISSUE TITLE
docker image with version of pritunl

### ISSUE THREAD

**Issue by cyr** [goofball222/pritunl#1]
i like this effort, it's well documented and easy to use. but would you mind tagging the docker image with the pritunl version instead of just latest? just makes it easier to figure out where you're at :)

thanks!

**Comment by goofball222** [comment]
The "latest" image is tagged with the pritunl version when built. `docker inspect` and examining the labels section will get you the version number:

```
docker inspect \
    --format '{{ index .Config.Labels "org.label-schema.version"}}' \
    goofball222/pritunl:latest
```

Alternatively I will create a specific release tag/image for each new version moving forward. If you check https://hub.docker.com/r/goofball222/pritunl/tags now there is a tag specific to v1.29.1979.98. Keep in mind that using the version specific tags will require a manual upgrade process in things like docker-compose.yml to specify the new tag vs. using latest and allowing it to pull updates automatically as needed/released.
