### ISSUE TITLE
Webinterface Port in Database is always set back to 443 after recreating the container

### ISSUE THREAD

**Issue by tristanXme** [goofball222/pritunl#10]
Hello,

I just setup your pirtunl image - great work, so thanks for that at first 👍

Sadly after every restart of the container, the port for the webinterface in the mongodb is set back to port 443.
The Problem is, that I want to run the OpenVPN on Port 443 (because other ports might be blocked on public wifis).

Any hint how to avoid the changes?

**Comment by tristanXme** [comment]
Also I just noticed, that when the Container is recreated, the "Public Adress" is overwritten. I inserted there a Domain, as my IP is changed every 24 hours - but after the recreation it gone. How to avoid that? Is there any ENV_Variable?

**Comment by ZorgeR** [comment]
Any chance to fix this issue?
need env variable to set port mapping.
Settings no saved after recreate
