### ISSUE TITLE
Problems trying to add server

### ISSUE THREAD

**Issue by caio-hat** [goofball222/pritunl#18]
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal

Docker version 20.10.17, build 100c701

        "Labels": {
                "org.opencontainers.image.created": "2022-07-21T17:00:01.334Z",
                "org.opencontainers.image.description": "Pritunl Server",
                "org.opencontainers.image.licenses": "Apache-2.0",
                "org.opencontainers.image.revision": "1d8656cd5c90f1b80ce2757f99699d76347be1d3",
                "org.opencontainers.image.source": "https://github.com/goofball222/pritunl",
                "org.opencontainers.image.title": "Pritunl Server",
                "org.opencontainers.image.url": "https://github.com/goofball222/pritunl",
                "org.opencontainers.image.vendor": "The Goofball - goofball222@gmail.com",
                "org.opencontainers.image.version": "1.30.3233.96"
            }
            
            
    * Details on how to reproduce the trouble, if available:
    * 
After the last update, when we click on "Add server" nothing happens, no screen is displayed, apparently no action occurs, making it impossible to configure the server data.

**Comment by goofball222** [comment]
This is an issue in upstream pritunl itself, not the Docker image build. Unfortunately, I can't fix it, it will have to wait for a release from pritunl upstream.

![image](https://user-images.githubusercontent.com/17112931/180490276-1139b051-2f6c-45fe-b045-0afabda781d7.png)

In the meantime, you can pull an older version tag and use it IE: ghcr.io/goofball222/pritunl:1.30.3226.71

https://github.com/goofball222/pritunl/pkgs/container/pritunl

**Comment by goofball222** [comment]
Looks like pritunl upstream release [v1.30.3235.85](https://github.com/pritunl/pritunl/releases/tag/1.30.3235.85) fixes this.

**Comment by goofball222** [comment]
Image latest, and 1.30.3235.85 tags are built with that version as well now.

**Comment by goofball222** [comment]
fixed by upstream 1.30.3235.85
