### ISSUE TITLE
Constant CPU usage 5-6%?

### ISSUE THREAD

**Issue by adminradio** [goofball222/pritunl#2]
Not a bug, but is it normal that running pritunl within docker, that the container uses constantly 5 to 6% of CPU-Time?

Docker version 18.09.3, build 774a1f4 on debian 9, 10 Core VPS, 32GB Ram

<img width="573" alt="cpu-pritunl" src="https://user-images.githubusercontent.com/2880143/55383381-57b45680-5528-11e9-9fbb-b0cbdfb699b3.png">

**Comment by goofball222** [comment]
Has been normal for me, I'm seeing 4-5% pritunl usage at idle on a 4c/4t i5-3570S CPU @ 3.10GHz when running in Docker across several different hosts.

**Comment by adminradio** [comment]
Ok, thank you.
