### ISSUE TITLE
Missing module - The "dnspython" module must be installed to use mongodb+srv:// URIs

### ISSUE THREAD

**Issue by krisread** [goofball222/pritunl#4]
When trying to use a Mongo DB uri with +srv in it

The "dnspython" module must be installed to use mongodb+srv:// URIs

**Comment by goofball222** [comment]
@krisread I added the dnspython Alpine package to the Dockerfile. Once Docker Hub/Cloud gets done rebuilding things (~1h after this post) the goofball222/pritunl:latest image on the public registry should be up to date with that change.

Can you please re-test with that latest image and let me know if that resolves your error?

**Comment by veriservus** [comment]
> @krisread I added the dnspython Alpine package to the Dockerfile. Once Docker Hub/Cloud gets done rebuilding things (~1h after this post) the goofball222/pritunl:latest image on the public registry should be up to date with that change.
> 
> Can you please re-test with that latest image and let me know if that resolves your error?

@goofball222 I can confirm that this is still an issue, fixed on derived Dockerfile with:
```
FROM goofball222/pritunl:latest

RUN rm -rf /usr/lib/python2.7/site-packages/pip/ \
    && rm -rf /usr/lib/python2.7/site-packages/pip-* \
    && apk add -q --no-cache --virtual .build-deps py-pip \
    && pip install --upgrade pip \
    && pip install dnspython \
    && apk del -q --purge .build-deps
```
