### ISSUE TITLE
Wireguard wg0 error

### ISSUE THREAD

**Issue by pennismen** [goofball222/pritunl#7]
Hello I am having problems when start wireguard, the instance can't start wg0. 

How can solve it?. 

Thanks in advanc

**Comment by goofball222** [comment]
The docker host server must have the wireguard kernel modules installed and loaded for wireguard support in the container to function. The how-to for installing and loading the WG modules is highly dependent on the docker host OS.

**Comment by pennismen** [comment]
Yes, you are agree i install repo + wireguard and now can grow up WG0 but at the moment of connect USING TRAEFIK + LetsEncrypt with Cloudflare give me error when connect.

Maybe can help me for continue.

**Comment by goofball222** [comment]
Can you provide your sanitized run command/docker-compose.yml?

**Comment by pennismen** [comment]
Here you have it, so sorry for post it later.

`
version: "3.7"
services:

# Traefik Reverse Proxy
  traefik:
    image: traefik:v1.7.16
    container_name: traefik
    hostname: traefik
    restart: unless-stopped
    networks:
      traefik_proxy:
        ipv4_address: 172.19.0.2
      vpn:
        ipv4_address: 172.20.0.2
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_API_KEY=${CLOUDFLARE_API_KEY}
    domainname: ${DOMAINNAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${USERDIR}/docker/traefik:/etc/traefik
      - ${USERDIR}/docker/shared:/shared
    labels:
      traefik.enable: "true"
      traefik.backend: traefik
      traefik.protocol: http
      traefik.port: 8080
      traefik.frontend.rule: Host:traefik.${DOMAINNAME}
      traefik.frontend.headers.SSLHost: traefik.${DOMAINNAME}
      traefik.docker.network: traefik_proxy
      traefik.frontend.passHostHeader: "true"
      traefik.frontend.headers.SSLForceHost: "true"
      traefik.frontend.headers.SSLRedirect: "true"
      traefik.frontend.headers.browserXSSFilter: "true"
      traefik.frontend.headers.contentTypeNosniff: "true"
      traefik.frontend.headers.forceSTSHeader: "true"
      traefik.frontend.headers.STSSeconds: 315360000
      traefik.frontend.headers.STSIncludeSubdomains: "true"
      traefik.frontend.headers.STSPreload: "true"
      traefik.frontend.headers.customResponseHeaders: X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex
      traefik.frontend.headers.frameDeny: "true"
      traefik.frontend.headers.customFrameOptionsValue: 'allow-from https:${DOMAINNAME}'
      traefik.frontend.auth.basic.users: "blanked"
	  
	  
# PriTunl Db + VPN
  mongo:
    image: mongo:latest
    container_name: pritunldb
    hostname: pritunldb
    networks:
      traefik_proxy:
        ipv4_address: 172.19.0.30
    volumes:
      - ${USERDIR}/docker/pritunl:/data/db

  pritunl:
    image: goofball222/pritunl:latest
    container_name: pritunl
    hostname: pritunl
    privileged: true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      traefik_proxy:
        ipv4_address: 172.19.0.31
    links:
      - mongo
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9765:443"
      - "1194:1194/udp"
      - "1195:1195/udp"
    environment:
      - TZ=${TZ}
      - MONGODB_URI=mongodb://mongo:27017/pritunl
      - REVERSE_PROXY=true
      - WIREGUARD=true
    labels:   
      traefik.enable: "true"
      traefik.backend: pritunl
      traefik.protocol: https
      traefik.port: 443
      traefik.frontend.rule: Host:pritunl.${DOMAINNAME}
      traefik.frontend.headers.SSLHost: pritunl.${DOMAINNAME}
      traefik.docker.network: traefik_proxy
      traefik.frontend.passHostHeader: "true"
      traefik.frontend.headers.SSLForceHost: "true"
      traefik.frontend.headers.SSLRedirect: "true"
      traefik.frontend.headers.browserXSSFilter: "true"
      traefik.frontend.headers.contentTypeNosniff: "true"
      traefik.frontend.headers.forceSTSHeader: "true"
      traefik.frontend.headers.STSSeconds: 315360000
      traefik.frontend.headers.STSIncludeSubdomains: "true"
      traefik.frontend.headers.STSPreload: "true"
      traefik.frontend.headers.customResponseHeaders: X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex
      traefik.frontend.headers.frameDeny: "true"
      traefik.frontend.headers.customFrameOptionsValue: 'allow-from https:${DOMAINNAME}'`

**Comment by goofball222** [comment]
Taking a guess at it, you probably need to add
`insecureSkipVerify = true`
to your traefik.toml configuration file. - https://docs.traefik.io/v1.7/configuration/commons/

That way the self-signed SSL certificate the pritunl container generates and uses in Wireguard mode will be accepted by Traefik without any validation.

If that doesn't work can you provide the text of the error message you get when you try to connect to the pritunl.${DOMAINNAME} hostname?
